# Project information
site_name: CyberSec
site_description: 'A collection of notes and writeups from my journey through cyber security concepts.'
site_url: https://nanoor.github.io/CyberSec/
site_author: Nouman Noor

# Copyright
copyright: "&copy; 2024 Nouman Noor"

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  #favicon: assets/favicon.png
  icon:
    logo: simple/gnubash

# Plugins
plugins:
  #- blog
  - git-revision-date-localized
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nanoor
    - icon: fontawesome/brands/linkedin
      link: https://ca.linkedin.com/in/nouman-noor-60193727
  # status:
  #   new: Recently added

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home: index.md
  - Notes:
    - Misc:
      - Shell Stabilisation: notes/misc/shellstabilisation.md
    - Network: 
      - DNS: notes/network/dns.md
      - OSI Model: notes/network/osimodel.md
    - Privilege Escalation (Linux):
      - Cron Jobs: notes/privesc_linux/crontab.md
      - Passwd/Shadow File: notes/privesc_linux/passwdshadow.md
      - Path Variable: notes/privesc_linux/pathvariable.md
      - SUID: notes/privesc_linux/suid.md
  - Walkthroughs: 
    - THM: 
      - Active Directory Basics: walkthroughs/thm/activedirectorybasics.md
      - Advent of Cyber 2022:
        - Day 1 - Frameworks: walkthroughs/thm/adventofcyber2022/day1.md
        - Day 2 - Log Analysis: walkthroughs/thm/adventofcyber2022/day2.md
        - Day 3 - OSINT: walkthroughs/thm/adventofcyber2022/day3.md
        - Day 4 - Scanning: walkthroughs/thm/adventofcyber2022/day4.md
        - Day 5 - Brute Force: walkthroughs/thm/adventofcyber2022/day5.md
        - Day 6 - Email Analysis: walkthroughs/thm/adventofcyber2022/day6.md
        - Day 7 - Cyber Chef: walkthroughs/thm/adventofcyber2022/day7.md
        - Day 8 - Smart Contracts: walkthroughs/thm/adventofcyber2022/day8.md
        - Day 9 - Pivoting: walkthroughs/thm/adventofcyber2022/day9.md
        - Day 10 - Hack a Game: walkthroughs/thm/adventofcyber2022/day10.md
        - Day 11 - Memory Forensics: walkthroughs/thm/adventofcyber2022/day11.md
        - Day 12 - Malware Analysis: walkthroughs/thm/adventofcyber2022/day12.md
        - Day 13 - Packet Analysis: walkthroughs/thm/adventofcyber2022/day13.md
        - Day 14 - Web Applications: walkthroughs/thm/adventofcyber2022/day14.md
        - Day 15 - Secure Coding (Securing File Upload): walkthroughs/thm/adventofcyber2022/day15.md
        - Day 16 - Secure Coding (SQLi): walkthroughs/thm/adventofcyber2022/day16.md
        - Day 17 - Secure Coding (Regular Expressions): walkthroughs/thm/adventofcyber2022/day17.md
        - Day 18 - Sigma: walkthroughs/thm/adventofcyber2022/day18.md
        - Day 19 - Hardware Hacking: walkthroughs/thm/adventofcyber2022/day19.md
        - Day 20 - Firmware Reverse Engineering: walkthroughs/thm/adventofcyber2022/day20.md
        - Day 21 - MQTT: walkthroughs/thm/adventofcyber2022/day21.md
      - Authentication Bypass: walkthroughs/thm/authenticationbypass.md
      - Basic Pentesting: walkthroughs/thm/basicpentesting.md
      - Blue: walkthroughs/thm/blue.md
      - Command Injection: walkthroughs/thm/commandinjection.md
      - Common Linux Privesc: walkthroughs/thm/commonlinuxprivesc.md
      - Cross-site Scripting: walkthroughs/thm/crosssitescripting.md
      - File Inclusion: walkthroughs/thm/fileinclusion.md
      - Hydra: walkthroughs/thm/hydra.md
      - IDOR: walkthroughs/thm/idor.md
      - John the Ripper: walkthroughs/thm/johntheripper.md
      - Kenobi: walkthroughs/thm/kenobi.md
      - Linux PrivEsc: walkthroughs/thm/linuxprivesc.md
      - Metasploit - Exploitation: walkthroughs/thm/metasploitexploitation.md
      - Metasploit - Meterpreter: walkthroughs/thm/metasploitmeterpreter.md
      - Mother's Secret: walkthroughs/thm/motherssecret.md
      - OWASP Juice Shop: walkthroughs/thm/owaspjuiceshop.md
      