# Project information
site_name: CyberSec
site_description: 'A collection of notes and writeups from my journey through cyber security concepts.'
site_url: https://nanoor.github.io/CyberSec/
site_author: Nouman Noor

# Copyright
copyright: "&copy; 2024 Nouman Noor"

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  #favicon: assets/favicon.png
  icon:
    logo: simple/gnubash

# Plugins
plugins:
  #- blog
  - git-revision-date-localized
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nanoor
    - icon: fontawesome/brands/linkedin
      link: https://ca.linkedin.com/in/nouman-noor-60193727
  # status:
  #   new: Recently added

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home: index.md
  - Notes:
    - Misc:
      - Shell Stabilisation: notes/misc/shellstabilisation.md
    - Network: 
      - DNS: notes/network/dns.md
      - OSI Model: notes/network/osimodel.md
    - Privilege Escalation (Linux):
      - Cron Jobs: notes/privesc_linux/crontab.md
      - Passwd/Shadow File: notes/privesc_linux/passwdshadow.md
      - Path Variable: notes/privesc_linux/pathvariable.md
      - SUID: notes/privesc_linux/suid.md
     